# Generated by Django 5.2.1 on 2025-06-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0002_publicacion_fecha_eliminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
